sudo: false
language: elixir
elixir: 1.4.0
otp_release: 19.0
addons:
  postgresql: '9.4'
env:
  global:
    - MIX_ENV=travis
    - PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST
before_script:
  - rvm install ruby-2.3.1
  - gem install pronto-credo
script:
  - if [ $PULL_REQUEST_ID != false ]; then pronto run -f github_pr; fi
  - mix test
  - mix dogma || true
